---
version: 0
files:
  - source: /
    destination: /home/ec2-user/deployment
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/execute_playbook.sh
      timeout: 300
      runas: ec2-user
