version: 0.2

env:
  variables:
    REPOSITORY_URI: "381492170336.dkr.ecr.us-east-1.amazonaws.com/sampleapp-registory"
    IMAGE_TAG: latest
    AWS_DEFAULT_REGION: us-east-1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo create Amazon ECR regirstryAWS_DEFAULT_REGION
      - aws ecr create-repository --repository-name sampleapp-registory --region $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Maven project...
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
